baseURL = "http://joshayres.tech/"
languageCode = "en-us"
title = "Josh Ayres"
theme = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software Engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Josh Ayres"
    subtitle = "Software Engineer"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "/home/josh"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

  [[params.social]]
    name = "email"
    url = "mailto:me@joshayers.tech"
  
  [[params.social]]
    name = "github"
    url = "https://github.com/joshayres"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/me/"
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "projects/"
#    [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "posts/"
